name: Build wheels

on:
  push:
    branches:
    - master
    tags:
    - v*

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build_wheels:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: osx-arm64, os: macos-14, arch: 'arm64' }
          - { name: osx-x64, os: macos-latest, arch: 'x86_64' }
          - { name: linux-x64, os: ubuntu-latest, arch: 'x86_64' }
          # - { name: windows-x64, os: windows-latest}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
      if: runner.os != 'Windows'

    - name: Set up build environment (Windows, MSYS2)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          autotools
          make
          git
          base-devel
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
      if: runner.os == 'Windows'
    
    - name: Set up build environment (Linux)
      run: |
        echo "CC=gcc-14" >> $GITHUB_ENV
        echo "CXX=g++-14" >> $GITHUB_ENV
      if: runner.os == 'Linux'
      
    - name: Set up build environment (MacOs)
      run: |
        brew install readline
        brew install automake
        brew install autogen
        uname -m
      if: runner.os == 'macOS'

    - name: Install cibuildwheel (Linux, Macos)
      run: pip install cibuildwheel
      if: runner.os != 'Windows'

    - name: Install cibuildwheel (Windows, MSYS2)
      shell: msys2 {0}
      run: python -m pip install cibuildwheel
      if: runner.os == 'Windows'

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Build wheels (Linux/MacOs)
      env:
        CIBW_ARCHS_MACOS: ${{ matrix.config.arch }}
      run: python -m cibuildwheel --output-dir wheelhouse
      shell: bash
      if: runner.os != 'Windows'

    - name: Build wheels (Windows)
      shell: msys2 {0}
      run: python -m cibuildwheel --output-dir wheelhouse
      if: runner.os == 'Windows'

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
        if-no-files-found: error